// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLL129Z31UVrJh7d4EBaCJ2cGM1MJs6w8',
    appId: '1:991375486953:web:bdd6182567e31bf7a32578',
    messagingSenderId: '991375486953',
    projectId: 'rhythmbhara-tara-sadhana-517d0',
    authDomain: 'rhythmbhara-tara-sadhana-517d0.firebaseapp.com',
    storageBucket: 'rhythmbhara-tara-sadhana-517d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACa7g12hffxZo_fumw-NjmoM3vL8CSSBc',
    appId: '1:991375486953:android:c0ba51d7be98e780a32578',
    messagingSenderId: '991375486953',
    projectId: 'rhythmbhara-tara-sadhana-517d0',
    storageBucket: 'rhythmbhara-tara-sadhana-517d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHMyIorXS2zBGJVILzopg-sLnM6LFhEE',
    appId: '1:991375486953:ios:050a779de5f10030a32578',
    messagingSenderId: '991375486953',
    projectId: 'rhythmbhara-tara-sadhana-517d0',
    storageBucket: 'rhythmbhara-tara-sadhana-517d0.firebasestorage.app',
    androidClientId: '991375486953-0l35shk2cumu0c4p6umlvq5f5klajn4u.apps.googleusercontent.com',
    iosClientId: '991375486953-ud1pq3a2s7011qq4egu33tggds9cr2js.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhythmbharaTaraSadhana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHMyIorXS2zBGJVILzopg-sLnM6LFhEE',
    appId: '1:991375486953:ios:050a779de5f10030a32578',
    messagingSenderId: '991375486953',
    projectId: 'rhythmbhara-tara-sadhana-517d0',
    storageBucket: 'rhythmbhara-tara-sadhana-517d0.firebasestorage.app',
    androidClientId: '991375486953-0l35shk2cumu0c4p6umlvq5f5klajn4u.apps.googleusercontent.com',
    iosClientId: '991375486953-ud1pq3a2s7011qq4egu33tggds9cr2js.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhythmbharaTaraSadhana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLL129Z31UVrJh7d4EBaCJ2cGM1MJs6w8',
    appId: '1:991375486953:web:65dd2e144db98aaba32578',
    messagingSenderId: '991375486953',
    projectId: 'rhythmbhara-tara-sadhana-517d0',
    authDomain: 'rhythmbhara-tara-sadhana-517d0.firebaseapp.com',
    storageBucket: 'rhythmbhara-tara-sadhana-517d0.firebasestorage.app',
  );

}